=== leonliusha/JavaPractice/Interview/SchemaPractice.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" 
			elementFormDefault="qualified" 
			xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Contacts" type="ContactsType"/>
	<xs:complexType name="ContactsType">
		<xs:sequence>
			<xs:element type="PersonType" name="Person" maxOccurs="unbounded" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="PersonType">
		<xs:sequence>
			<xs:element name="name"/>
			<xs:element type="addressType" name="address" minOccurs="1"/>
			<xs:element name="score"/>
		</xs:sequence>
		<xs:attribute type="xs:string" name="id" use="optional"/>
		<xs:attribute type="xs:string" name="age" use="optional"/>
	</xs:complexType>
	
	<xs:complexType name="addressType">
		<xs:choice maxOccurs="unbounded" minOccurs="1">
			<xs:element type="xs:string" name="address1"/>
			<xs:element type="xs:string" name="phone"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:element name="product">
		<xs:complexType>
			<xs:attribute name="prodid" type="xs:positiveInteger"/>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="employee" type="fullpersoninfo"/>
	<xs:complexType name="personinfo">
		<xs:sequence>
			<xs:element name="firstname" type="xs:string"/>
			<xs:element name="lastname" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="fullpersoninfo">
		<xs:complexContent>
			<xs:extension base="personinfo">
				<xs:sequence>
					<xs:element name="address" type="xs:string"/>
					<xs:element name="city" type="xs:string"/>
					<xs:element name="country" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	
	</xs:complexType>
</xs:schema>

=== leonliusha/JavaPractice/Interview/interviewXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<Contacts
xmlns="http://www.w3school.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn SchemaPractice.xsd">

<Person id="1" age="30">
	<name>John Smith</name>
	<address>
		<phone>33101</phone>
		<address1>abcd</address1>
	</address>
	<score>80</score>
</Person>

<Person id="2" age="18">
	<name>Amend Doe</name>
	<address/>
	<score>55</score>
</Person>

<Person id="3" age="35">
	<name>Allen Yeh</name>
	<score>10</score>
	<address>
		<address1>abcd</address1>
		<phone>331</phone>
	</address>
</Person>
</Contacts>
